### ISSUE TITLE
About the .js file

### ISSUE THREAD

**Issue by LJHXUEXIPY** [tdavislab/Hypergraph-Vis#6]
This file（simplified_hypergraph.js） does not exist. Can you provide it if possible
127.0.0.1 - - [28/Mar/2024 11:06:08] "GET /static/js\\simplified_hypergraph.js HTTP/1.1" 404 -
![Snipaste_2024-03-28_11-07-28](https://github.com/tdavislab/Hypergraph-Vis/assets/86903836/00ae2b07-6fdf-4b25-8478-7e2d8e066d81)

**Comment by zhou325** [comment]
Hello,

Sorry for the confusion. I believe this js file is deprecated and no longer used in the software. I just updated the code to stop calling it from assets.py

Thanks!
